import * as console from 'node:console';
import * as fs from 'node:fs';
import path from 'node:path';
import * as process from 'node:process';
import { getStackFileName } from '@opra/common';
import colors from 'ansi-colors';
import { program } from 'commander';
import { extractDocumentTranslations } from './docs-extractor/extract-command.js';
import { TsGenerator } from './ts-generator/ts-generator.js';

const dirname = path.dirname(getStackFileName());
const pkgJson = fs.existsSync(path.resolve(dirname, './package.json'))
  ? JSON.parse(
      fs.readFileSync(path.resolve(dirname, './package.json'), 'utf-8'),
    )
  : JSON.parse(
      fs.readFileSync(path.resolve(dirname, '../package.json'), 'utf-8'),
    );

program.version(pkgJson.version);

program
  .command('generate', { isDefault: true })
  .description('Generates a TypeScript client from an OPRA service')
  .argument('<serviceUrl>', 'OPRA service url')
  .argument('<outDir>', 'Output directory')
  .option('--ext', 'Adds js extension to imports')
  .option('--refns', 'Exports referenced API documentation with namespaces')
  .option(
    '--lang <lang>',
    'Language to fetch the documentation texts in (e.g. tr)',
  )
  .option('--no-color', 'Disables colors in logs messages')
  .action(async (serviceUrl, outDir, options) => {
    if (!options.color) colors.enabled = false;
    const generator = new TsGenerator({
      serviceUrl,
      logger: console,
      outDir,
      importExt: options.ext,
      referenceNamespaces: options.refns,
      lang: options.lang,
      fileHeader: `/* Generated by OPRA Code Generator, Version ${pkgJson.version} */`,
    });
    await generator
      .generate()
      .then(() => console.log(colors.greenBright('Completed')))
      .catch(e => console.error(e.message));
  });

program
  .command('docs:extract')
  .description(
    'Extracts a documentation translation skeleton from a local module ' +
      'exporting an ApiDocument',
  )
  .argument(
    '<module>',
    'Module to import, optionally with the export to use (./api-document.js#CustomerApiDocument)',
  )
  .argument('<outFile>', 'Translation file to write (e.g. ./docs/en.json)')
  .option('--no-color', 'Disables colors in logs messages')
  .action(async (module, outFile, options) => {
    if (!options.color) colors.enabled = false;
    await extractDocumentTranslations(module, outFile, console).catch(e =>
      console.error(colors.red(e.message)),
    );
  });

program
  .command('docs:studio')
  .description(
    'Opens a local documentation editor for a local module exporting an ' +
      'ApiDocument, writing edits back to the source-language bundle',
  )
  .argument(
    '<module>',
    'Module to import, optionally with the export to use (./api-document.js#CustomerApiDocument)',
  )
  .option(
    '--docs <dir>',
    'Directory holding the translation files (e.g. ./docs)',
    './docs',
  )
  .option('--lang <lang>', "Bundle to edit (default: the document's own)")
  .option('--port <port>', 'Port to listen on', '7300')
  .option('--scope <scope>', 'Scope to render, for a multi-scope document')
  .option('--no-color', 'Disables colors in logs messages')
  .action(async (module, options) => {
    if (!options.color) colors.enabled = false;
    const { startDocsStudio } = await import('./docs-studio/studio-command.js');
    await startDocsStudio(module, {
      docsDir: options.docs,
      lang: options.lang,
      port: Number(options.port),
      scope: options.scope,
      logger: console,
    }).catch(e => console.error(colors.red(e.message)));
  });

if (process.argv.length < 3) program.help();
else program.parse(process.argv);
