import 'reflect-metadata';
import './decorators/http-operation-entity.decorator.js';
import './decorators/http-operation-entity-create.decorator.js';
import './decorators/http-operation-entity-delete.decorator.js';
import './decorators/http-operation-entity-delete-many.decorator.js';
import './decorators/http-operation-entity-find-many.decorator.js';
import './decorators/http-operation-entity-get.decorator.js';
import './decorators/http-operation-entity-replace.decorator.js';
import './decorators/http-operation-entity-update.decorator.js';
import './decorators/http-operation-entity-update-many.decorator.js';
import * as MQControllerDecorator_ from './decorators/mq-controller.decorator.js';
import * as MQOperationDecorator_ from './decorators/mq-operation.decorator.js';
import * as WSControllerDecorator_ from './decorators/ws-controller.decorator.js';
import * as WSOperationDecorator_ from './decorators/ws-operation.decorator.js';
import * as DataTypeFactory_ from './factory/data-type.factory.js';
import * as HttpApiFactory_ from './factory/http-api.factory.js';

export * from './api-document.js';
export * from './common/api-base.js';
export * from './common/data-type-map.js';
export * from './common/document-element.js';
export * from './common/document-init-context.js';
export * from './common/document-node.js';
export * from './common/extract-translations.js';
export * from './common/opra-document-error.js';
export * from './common/translate-doc.js';
export * from './constants.js';
export * from './data-type/api-field.js';
export * from './data-type/array-type.js';
export * from './data-type/complex-type.js';
export * from './data-type/data-type.js';
export * from './data-type/enum-type.js';
export * from './data-type/extended-types/index.js';
export * from './data-type/mapped-type.js';
export * from './data-type/mixin-type.js';
export * from './data-type/omit-type.js';
export * from './data-type/partial-type.js';
export * from './data-type/pick-type.js';
export * from './data-type/primitive-types/index.js';
export * from './data-type/required-type.js';
export * from './data-type/simple-type.js';
export * from './data-type/union-type.js';
export type { MQControllerDecorator } from './decorators/mq-controller.decorator.js';
export type { MQOperationDecorator } from './decorators/mq-operation.decorator.js';
export type { WSControllerDecorator } from './decorators/ws-controller.decorator.js';
export type { WSOperationDecorator } from './decorators/ws-operation.decorator.js';
export * from './decorators/ws-param.decorator.js';
export * from './factory/api-document.factory.js';
export * from './http/http-api.js';
export * from './http/http-controller.js';
export * from './http/http-media-type.js';
export * from './http/http-multipart-field.js';
export * from './http/http-operation.js';
export * from './http/http-operation-response.js';
export * from './http/http-parameter.js';
export * from './http/http-request-body.js';
export * from './http/http-status-range.js';
export * from './mq/mq-api.js';
export * from './mq/mq-controller.js';
export * from './mq/mq-header.js';
export * from './mq/mq-operation.js';
export type { MQOperationResponse } from './mq/mq-operation-response.js';
export * from './ws/ws-api.js';
export * from './ws/ws-controller.js';
export * from './ws/ws-operation.js';

export namespace classes {
  export import HttpApiFactory = HttpApiFactory_.HttpApiFactory;
  export import DataTypeFactory = DataTypeFactory_.DataTypeFactory;
  export import MQOperationDecoratorFactory = MQOperationDecorator_.MQOperationDecoratorFactory;
  export import MQControllerDecoratorFactory = MQControllerDecorator_.MQControllerDecoratorFactory;
  export import WSOperationDecoratorFactory = WSOperationDecorator_.WSOperationDecoratorFactory;
  export import WSControllerDecoratorFactory = WSControllerDecorator_.WSControllerDecoratorFactory;
}
